import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { getServerSession } from 'next-auth';
import { SessionProvider } from 'next-auth/react';
import { AppTheme } from '@/components/global/app-theme';
import { StoreProvider } from '@/stores';
import { ErrorBoundary } from '@/components/global/error-boundary';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ErrorBoundary>
          <StoreProvider>
            <SessionProvider session={session}>
              <AppTheme>{children}</AppTheme>
            </SessionProvider>
          </StoreProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
